---
- name: Get repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  tags: install

- name: Add repository
  apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
  tags: install

- name: Install MongoDB
  update_cache: yes
  apt:
      name: mongodb-org
  tags: install

- name: Enable&Run MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
